### ISSUE TITLE
The hang inside NativeTcpIpStackImpl.close()

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#1663]
See https://github.com/AdguardTeam/AdguardForAndroid/issues/4206 for details

**Comment by michael1900** [comment]
I apologize but I have a strange big premonition, how long will I have to wait to get AdGuard, regularly paid, working again? A month has already passed.
Thanks

@sfionov @Stillness-2 @artemiv4nov @maxikuzmin

**Comment by ameshkov** [comment]
This is a valid concern, the fix will be included into the next minor update.

**Comment by michael1900** [comment]
> This is a valid concern, the fix will be included into the next minor update.

Nightly build?

**Comment by ameshkov** [comment]
It will go through nightly when it's ready, of course.

**Comment by michael1900** [comment]
Is it fixed?

**Comment by michael1900** [comment]
Hi, i see Status Resolved, in how many days will it be available in the next nightly? @ameshkov

**Comment by sfionov** [comment]
@michael1900 This is very rare issue. We notify you when next nightly is out - it will include additional logging to analyze this issue

**Comment by michael1900** [comment]
> @michael1900 This is very rare issue. We notify you when next nightly is out - it will include additional logging to analyze this issue

Ok but i can't use it normally and what means additional logging..? The bug is fixed or not? I can't understand. Thanks

**Comment by michael1900** [comment]
Any good news? @sfionov

**Comment by michael1900** [comment]
What a shame. Really what a shame. @sfionov @artemiv4nov @admitrevskiy @maxikuzmin @Chinaski1 @Stillness-2 @ameshkov

**Comment by sfionov** [comment]
@michael1900 Please don't spam.

Found your log again. Unfortunately, it doesn't contain hang in the same place, so it is still not clear what happened.

Please check our KB for battery tips https://kb.adguard.com/en/android/solving-problems/background-work

**Comment by michael1900** [comment]
> @michael1900 
> 
> 
> 
> Please check our KB for battery tips https://kb.adguard.com/en/android/solving-problems/background-work

Are you serious?
