### ISSUE TITLE
www.secdwp.net

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1711]
@adguard-bot commented on [Thu Dec 22 2022](https://github.com/AdguardTeam/AdguardFilters/issues/138030)

### Issue URL (Incorrect Blocking)
 [https://www.secdwp.net/login](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.secdwp.net%2Flogin)
### Comment
Username: @engas
> secdwp.net/login doesn't open properly when AdGuard enabled. It seems that AdGuard blocks plugin loading because I installed plugin already but web page requires when AdGuard enabled.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/XZVJ0So.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/7yDzk52.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.11.3
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode: | disabled
DNS filtering: | server: `https://53a3a333.d.adguard-dns.com/dns-query`<br>filters: `https://filters.adtidy.org/windows/filters/15.txt, User+rules`
Filters: | <b>Ad Blocking:</b><br/>EasyList, <br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Other:</b><br/>AdGuard Experimental<br/><br/><b>Language-specific:</b><br/>List-KR, <br/>YousList, <br/>Dandelion Sprout's Nordic Filters, <br/>AdGuard German, <br/>AdGuard Japanese, <br/>AdGuard Dutch, <br/>AdGuard Spanish/Portuguese
Userscripts: | disabled

---

@AdamWr commented on [Thu Dec 22 2022](https://github.com/AdguardTeam/AdguardFilters/issues/138030#issuecomment-1362493458)

It looks like that problem is not related to filters and SSL certificate for `127.0.0.1` (which I guess is installed and used by this plugin) isn't trusted by the browser when AdGuard is used.

<details><summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/29142494/209076516-7fca5046-6588-4b4b-935a-a0aca2f2bd55.png)

![image](https://user-images.githubusercontent.com/29142494/209076531-844a5d6d-d322-4726-8cc5-3b4ec36933c1.png)

</details>

Could you please try to open AdGuard's settings and in `General Settings` go to `Advanced Settings` and disable `Filter localhost` option and then save settings (like on a screenshots below)?

<details><summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/29142494/209076784-00641a2b-ac0d-48fa-8eac-3e9f9c31439f.png)

![image](https://user-images.githubusercontent.com/29142494/209076794-5e2578ba-9dae-4c1f-b54e-45513807567e.png)

</details>

Or you can also try to add `127.0.0.1` to HTTPS exclusions - Settings -> `Network` tab - HTTPS filtering section - `Exclusions` (screenshots below).

<details><summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/29142494/209077085-c1d5f01e-ee1d-413c-96c8-78c667519928.png)

![image](https://user-images.githubusercontent.com/29142494/209077094-29b7adfe-dcf8-4c16-9bd2-5a349497293d.png)

</details>

---

@piquark6046 commented on [Thu Dec 22 2022](https://github.com/AdguardTeam/AdguardFilters/issues/138030#issuecomment-1362579923)

@AdamWr The website is used by Samsung Electronics employees as https://www.secdwp.net said. [^1]

[^1]: A VPN connection with a non-South Korean IP is required.

---

@AdamWr commented on [Thu Dec 22 2022](https://github.com/AdguardTeam/AdguardFilters/issues/138030#issuecomment-1362587876)

I'm aware of this and I was able to reproduce this issue,
I just wanted to know if this solution works and then move it to correct repository.

**Comment by ngorskikh** [comment]
@AdamWr Hi! Seeing as you have already installed the software and reproduced the issue, can you please collect AdGuard's logs with `/trace` and Chrome's net-export? I just really don't want to put Samsung's corporate spyware on my machine :)

**Comment by ngorskikh** [comment]
@AdamWr @engas Sorry for the wait. Does it work correctly after the initial failure? I see the issue is that AdGuard does MITM incorrectly, but it then adds an HTTPS exception because the client doesn't accept our certificate. It should work on the second and subsequent tries.
Also disabling "filter loopback (localhost)" in the advanced settings should solve this issue. Although I see this option can't be disabled when AdGuard VPN is installed, for some reason... Adding a network rule like `@@127.0.0.0/8$network` should be a viable workaround.

**Comment by AdamWr** [comment]
> Does it work correctly after the initial failure? I see the issue is that AdGuard does MITM incorrectly, but it then adds an HTTPS exception because the client doesn't accept our certificate. It should work on the second and subsequent tries.

It seems that it doesn't work, I have refreshed website few times and restarted web browser, but the problem still occurs.

>Adding a network rule like `@@127.0.0.0/8$network` should be a viable workaround.

It looks like that such rule cannot be added.
![image](https://user-images.githubusercontent.com/29142494/217822979-e2e670cf-0b50-460b-996b-9921fd3745aa.png)

This - `@@127.0.0.1$network` works on my end.

**Comment by ngorskikh** [comment]
@AdamWr Could you please send the logs where it doesn't work on the second and further tries?

**Comment by AdamWr** [comment]
Sure thing, done.
Time about 14:39, I have refreshed website few times.
[adg_logs_7.12.4170.0_0209_1439.zip](https://github.com/AdguardTeam/CoreLibs/files/10697743/adg_logs_7.12.4170.0_0209_1439.zip)

**Comment by ngorskikh** [comment]
@AdamWr Thanks! Also, on second thought, the `$network` exclusion is not a good solution: it will prevent AdGuard from filtering any site when AdGuard VPN is running, due to the way AdGuard VPN redirects all connections to loopback.

**Comment by ngorskikh** [comment]
So I've looked into this more, and it should be fixed (in the sense that it will work after the first failure) in CoreLibs 1.11 (which are coming soon to the applications).
